name: elrazy_clinics
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # packages for icons
  ionicons: ^0.2.2
  cupertino_icons: ^1.0.8
  line_icons: ^2.0.3
  # packages for fonts management
  font_awesome_flutter: ^10.7.0

  # packages for ui desings
  awesome_dialog: ^3.2.1
  flutter_onboarding_slider: ^1.0.11
  drop_down_list: ^0.0.6
  google_nav_bar: ^5.0.6
  flutter_custom_clippers: ^2.1.0

  # package for keep data in local source
  shared_preferences: ^2.2.3
  # packages for firebase management
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  firebase_messaging: ^14.9.2
  firebase_auth: ^4.19.5
  google_sign_in: ^6.2.1
  # packages for state management using bloc or cubit
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  # package for get pics from phone
  image_picker: ^1.1.1
  # packages for file download and opening
  path_provider: ^2.1.3
  http: ^1.2.1
  open_filex: ^4.4.0
  # packages for video player
  video_player: ^2.8.6
  flick_video_player: ^0.8.0
  # package for chat bot  powered by gemini
  google_gemini: ^0.1.2
  # package for text translation
  url_launcher: ^6.3.0
  # package to manage calender for appointments
  table_calendar: ^3.0.9

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  intl_utils: ^2.8.7
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/images/
  fonts:
    - family: Lumanosimo
      fonts:
        - asset: assets/fonts/Lumanosimo-Regular.ttf
    - family: Edu
      fonts:
        - asset: assets/fonts/EduTASBeginner-VariableFont_wght.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Bold.ttf
    - family: Georgia
      fonts:
        - asset: assets/fonts/Georgia.ttf
    - family: Garet
      fonts:
        - asset: assets/fonts/garet/Garet-Book.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
