// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVrtPu11_1hKo9-9y3IrNDH47Y3sfm_Lw',
    appId: '1:463396774250:web:fbed45793f3a019abb8513',
    messagingSenderId: '463396774250',
    projectId: 'elrazzyclinics',
    authDomain: 'elrazzyclinics.firebaseapp.com',
    storageBucket: 'elrazzyclinics.appspot.com',
    measurementId: 'G-S603SJ5V5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8yOj1HNul2sQFWPaoheqiVyCEAvESrBE',
    appId: '1:463396774250:android:2a52bd34a71816babb8513',
    messagingSenderId: '463396774250',
    projectId: 'elrazzyclinics',
    storageBucket: 'elrazzyclinics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkS5hw9ONrjdn9s35K2ZDFWpAzaA_Fy80',
    appId: '1:463396774250:ios:e40de3a5a4bf8388bb8513',
    messagingSenderId: '463396774250',
    projectId: 'elrazzyclinics',
    storageBucket: 'elrazzyclinics.appspot.com',
    iosBundleId: 'com.example.elrazyClinics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkS5hw9ONrjdn9s35K2ZDFWpAzaA_Fy80',
    appId: '1:463396774250:ios:e40de3a5a4bf8388bb8513',
    messagingSenderId: '463396774250',
    projectId: 'elrazzyclinics',
    storageBucket: 'elrazzyclinics.appspot.com',
    iosBundleId: 'com.example.elrazyClinics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVrtPu11_1hKo9-9y3IrNDH47Y3sfm_Lw',
    appId: '1:463396774250:web:5d64a00786f39f9ebb8513',
    messagingSenderId: '463396774250',
    projectId: 'elrazzyclinics',
    authDomain: 'elrazzyclinics.firebaseapp.com',
    storageBucket: 'elrazzyclinics.appspot.com',
    measurementId: 'G-4EZ0Q02XSR',
  );
}
